### PR TITLE
[chore] Update package name and fix a minor typo in the README file

### LINKED ISSUE #26: typo: mention of "Vue 3" in README for mellow-react and mellow-svelte
You can find mention of "Vue 3" on the READMEs of the `mellow-react` and `mellow-svelte`. 

[templates\mellow-react\README.md](https://github.com/babblebey/boring-stack/tree/develop/templates/mellow-react#readme)
```md
This template should help get you started developing with a modern Sails fullstack application with Inertia and Vue 3
```

[templates\mellow-svelte\README.md](https://github.com/babblebey/boring-stack/tree/develop/templates/mellow-svelte#readme)
```md
This template should help get you started developing with a modern Sails fullstack application with Inertia and Vue 3
```

It should read the respective libraries for sure.

### PR DESCRIPTION
**Pull request by Emmo00**
Fixes #26

### CODE REVIEW

**Comment by Emmo00** [comment]
Fixes #26

**Comment by DominusKelvin** [comment]
@Emmo00 awesome PR, you may have to change your commit as it doesn't follow the conventional commits guideline we use in The Boring JavaScript Stack.

See [here]( https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) on how to change the commit message and also check out `CONTRIBUTING.md` in repo on what format your commit message should be.

**Comment by Emmo00** [comment]
hello @DominusKelvin , is this Okay?

**Comment by DominusKelvin** [comment]
Much better, Thanks @Emmo00

**Review by DominusKelvin — APPROVED** [review]
This is great, thanks for the PR @Emmo00

**Pull request merged**
