### PR TITLE
Corrected the link to webpack

### PR DESCRIPTION
**Pull request by delight**
Link was pointing to an akward page

### CODE REVIEW

**Comment by DominusKelvin** [comment]
Hey @delight great job on this PR. However you didn't create an issue first as recommended by the CONTRIBUTING.md guide. Could you have a look at it and then tailor the PR as recommended?

**Comment by delight** [comment]
@DominusKelvin isn't that a little idiomatic for such a small obvious error fix?

Ultimately you can keep the error, or fix it yourself and claim that yo found / fixed it 🤣

up to you ... i is good to have contribution guide lines but you should also think pragmatically.

BTW: Are there any plans to get the Svelte Part up to feature parity with the others or is it just a "we have svelte too" thingy?

**Comment by DominusKelvin** [comment]
Got you, for all supported UI frameworks they will all have the mellow templates and all future templates 

For your PR please do create the issue as recommended by the CONTRIBUTING.md guide

Thanks

**Comment by delight** [comment]
https://github.com/sailscastshq/boring-stack/issues/61

**Comment by DominusKelvin** [comment]
sorry for the long wait @delight. Now merging

**Pull request merged**
