### PR TITLE
Chore: Remove duplicate text on README

### LINKED ISSUE #23: Fix typo error on ReadMe
In the description of The Boring JavaScript Stack in the ReadMe, there is a duplicate word `on the experience of`
> This stack is based on the experience of on the experience of Kelvin Omereshone and contributors.

### PR DESCRIPTION
**Pull request by d-a-ve**
Closes #23, #24

### CODE REVIEW

**Comment by DominusKelvin** [comment]
Hey @d-a-ve great job on this PR. Your PR does two things instead of one like the title of your PR said. Can you make this one PR fix the duplicate and then submit another one for adding the "Creating issues"
section to the contributing guide?

**Comment by d-a-ve** [comment]
Thank you reviewing @DominusKelvin. It was a mistake on my part and I will make another PR just for that issue.

Do you know a way I can go about uncommitting that last commit so it would just be the first commit that addresses the duplicate text that will be there?

I checked stackoverflow and the solutions I got was to use `git reset --hard HEAD^`. I haven't tried it yet.

**Comment by DominusKelvin** [comment]
Hmm 🤔 

To do that I think you can do this 

git reset --soft HEAD~1 command

Or use the GitHub app to make things easier

**Comment by d-a-ve** [comment]
Yeah I did the former and it worked so now I just want to make my remote in sync with the main repo then submit a pull request.

**Pull request closed without merging**
